In [3]:
import numpy as np

In [5]:
A = np.array([
    [0,0,1,0,1,0,0,0,1,0],  # 0
    [0,0,0,0,1,1,0,1,0,0],  # 1
    [0,0,0,0,0,1,0,0,0,0],  # 2
    [0,0,0,0,0,0,0,1,1,1],  # 3
    [0,0,0,0,0,0,0,0,1,0],  # 4
    [0,0,0,0,0,0,0,0,0,0],  # 5
    [0,0,0,0,0,0,0,0,1,0],  # 6
    [0,0,0,0,0,0,0,0,1,0],  # 7
    [0,0,0,0,0,0,0,0,0,0],  # 8
    [0,0,0,0,0,0,0,0,0,0],  # 9
])

In [7]:
# A^2 = 2-hop paths
A2 = np.linalg.matrix_power(A, 2)

In [9]:
# Print some examples
print("A^2 (2-hop paths):")
print(A2)

A^2 (2-hop paths):
[[0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [11]:
# A^3 = 3-hop paths
A3 = np.linalg.matrix_power(A, 3)

In [13]:
print("\nA^3 (3-hop paths):")
print(A3)


A^3 (3-hop paths):
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
