In [21]:
import numpy as np

In [23]:
A = np.array([
    [0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [1,1,0,0,0,0,0,0,0,0],
    [0,1,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0,0],
    [0,1,0,1,0,0,0,0,0,0],
    [1,0,0,1,1,0,1,1,0,0],
    [0,0,0,1,0,0,0,0,0,0]# 9
])

In [25]:
# linalg in numpy is for doing linear algebra

In [27]:
# A^2 = 2-hop paths
A2 = np.linalg.matrix_power(A, 2)

In [29]:
# Print some examples
print("A^2 (2-hop paths):")
print(A2)

A^2 (2-hop paths):
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 2 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [31]:
# A^3 = 3-hop paths
A3 = np.linalg.matrix_power(A, 3)

In [33]:
print("\nA^3 (3-hop paths):")
print(A3)


A^3 (3-hop paths):
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [35]:
A_undirected = A + A.T
A_undirected[A_undirected > 0] = 1 

In [37]:
A_undirected

array([[0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]])